# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_gui.ui'
#
# Created: Sun Jul  5 08:40:12 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(453, 538)
        MainWindow.setMinimumSize(QtCore.QSize(353, 538))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/calculator.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(16, 16))
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.toolButton = QtGui.QToolButton(self.tab)
        self.toolButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"background:transparent;\n"
"border:none;\n"
"\n"
"}"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/subject.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setIconSize(QtCore.QSize(48, 48))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout.addWidget(self.toolButton)
        self.lineEdit_subject_name = QtGui.QLineEdit(self.tab)
        self.lineEdit_subject_name.setObjectName(_fromUtf8("lineEdit_subject_name"))
        self.horizontalLayout.addWidget(self.lineEdit_subject_name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.toolButton_3 = QtGui.QToolButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton_3.setStyleSheet(_fromUtf8("QToolButton{\n"
"background:transparent;\n"
"border:none;\n"
"\n"
"}"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/credit_hours.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout_4.addWidget(self.toolButton_3)
        self.comboBox_credit_hours = QtGui.QComboBox(self.tab)
        self.comboBox_credit_hours.setObjectName(_fromUtf8("comboBox_credit_hours"))
        self.comboBox_credit_hours.addItem(_fromUtf8(""))
        self.comboBox_credit_hours.addItem(_fromUtf8(""))
        self.comboBox_credit_hours.addItem(_fromUtf8(""))
        self.comboBox_credit_hours.addItem(_fromUtf8(""))
        self.comboBox_credit_hours.addItem(_fromUtf8(""))
        self.comboBox_credit_hours.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox_credit_hours)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.toolButton_2 = QtGui.QToolButton(self.tab)
        self.toolButton_2.setStyleSheet(_fromUtf8("QToolButton{\n"
"background:transparent;\n"
"border:none;\n"
"\n"
"}"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/gpa_obtained.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon3)
        self.toolButton_2.setIconSize(QtCore.QSize(48, 48))
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout_3.addWidget(self.toolButton_2)
        self.comboBox_grade = QtGui.QComboBox(self.tab)
        self.comboBox_grade.setObjectName(_fromUtf8("comboBox_grade"))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.comboBox_grade.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox_grade)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setStyleSheet(_fromUtf8("QToolButton{\n"
"background:transparent;\n"
"border:none;\n"
"\n"
"}"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/table_pop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_gpa_results = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_gpa_results.setFont(font)
        self.lineEdit_gpa_results.setObjectName(_fromUtf8("lineEdit_gpa_results"))
        self.horizontalLayout_2.addWidget(self.lineEdit_gpa_results)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setStyleSheet(_fromUtf8("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"}"))
        self.pushButton_3.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/iib-logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(130, 60))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout_5.addWidget(self.pushButton_3)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_5.addWidget(self.label_11)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pushButton_4 = QtGui.QPushButton(self.tab_2)
        self.pushButton_4.setStyleSheet(_fromUtf8("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"}"))
        self.pushButton_4.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/email.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.pushButton_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_2.setStyleSheet(_fromUtf8("QPushButton{\n"
"background: transparent;\n"
"border: none;\n"
"}"))
        self.pushButton_2.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/cc_license.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon7)
        self.pushButton_2.setIconSize(QtCore.QSize(88, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_5.addWidget(self.pushButton_2)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GPA Calculator", None))
        self.toolButton.setToolTip(_translate("MainWindow", "Enter course name", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.lineEdit_subject_name.setToolTip(_translate("MainWindow", "Enter course name", None))
        self.lineEdit_subject_name.setPlaceholderText(_translate("MainWindow", "Enter course name", None))
        self.toolButton_3.setToolTip(_translate("MainWindow", "Choose credit hours for the course", None))
        self.toolButton_3.setText(_translate("MainWindow", "...", None))
        self.comboBox_credit_hours.setToolTip(_translate("MainWindow", "Choose credit hours for the course", None))
        self.comboBox_credit_hours.setItemText(0, _translate("MainWindow", "Choose credit hours", None))
        self.comboBox_credit_hours.setItemText(1, _translate("MainWindow", "1", None))
        self.comboBox_credit_hours.setItemText(2, _translate("MainWindow", "2", None))
        self.comboBox_credit_hours.setItemText(3, _translate("MainWindow", "3", None))
        self.comboBox_credit_hours.setItemText(4, _translate("MainWindow", "4", None))
        self.comboBox_credit_hours.setItemText(5, _translate("MainWindow", "5", None))
        self.toolButton_2.setToolTip(_translate("MainWindow", "Choose the grade obtained in the course", None))
        self.toolButton_2.setText(_translate("MainWindow", "...", None))
        self.comboBox_grade.setToolTip(_translate("MainWindow", "Choose the grade obtained in the course", None))
        self.comboBox_grade.setItemText(0, _translate("MainWindow", "Choose grade obtained", None))
        self.comboBox_grade.setItemText(1, _translate("MainWindow", "A", None))
        self.comboBox_grade.setItemText(2, _translate("MainWindow", "A-", None))
        self.comboBox_grade.setItemText(3, _translate("MainWindow", "B+", None))
        self.comboBox_grade.setItemText(4, _translate("MainWindow", "B", None))
        self.comboBox_grade.setItemText(5, _translate("MainWindow", "B-", None))
        self.comboBox_grade.setItemText(6, _translate("MainWindow", "C+", None))
        self.comboBox_grade.setItemText(7, _translate("MainWindow", "C", None))
        self.comboBox_grade.setItemText(8, _translate("MainWindow", "C-", None))
        self.comboBox_grade.setItemText(9, _translate("MainWindow", "D+", None))
        self.comboBox_grade.setItemText(10, _translate("MainWindow", "D", None))
        self.comboBox_grade.setItemText(11, _translate("MainWindow", "D-", None))
        self.comboBox_grade.setItemText(12, _translate("MainWindow", "WF/F", None))
        self.pushButton.setToolTip(_translate("MainWindow", "Click to add the above information to the table and calculate the GPA", None))
        self.pushButton.setText(_translate("MainWindow", "Push to table and calculate GPA", None))
        self.tableWidget.setToolTip(_translate("MainWindow", "Table containing a list of courses, their credit hours, and obtained grades", None))
        self.label.setToolTip(_translate("MainWindow", "This is grade point average of GPA calculated from the table data", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Your GPA is:</span></p></body></html>", None))
        self.lineEdit_gpa_results.setToolTip(_translate("MainWindow", "This is grade point average of GPA calculated from the table data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "GPA Calculator", None))
        self.label_5.setText(_translate("MainWindow", "   Created by Rimshah Sabir and Khalida Bibi at", None))
        self.label_11.setText(_translate("MainWindow", "CECOS University of IT & Emerging Sciences\n"
"Peshawar, Pakistan.", None))
        self.label_8.setText(_translate("MainWindow", "rimshah.sabir@gmail.com", None))
        self.label_9.setText(_translate("MainWindow", "khalida.bibi@cecos.edu.pk", None))
        self.label_15.setText(_translate("MainWindow", "This work is licensed under a \n"
"Creative Commons\n"
"Attribution 4.0 International License.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "About", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

